-- Schema do banco - Tech Challenge Fase 2
--
-- O MySQL executa este script na primeira inicialização do contêiner, com o
-- volume vazio. Os testes de integração usam o mesmo script. O Hibernate não
-- cria tabelas, só confere o mapeamento.
